// Mock data for the Tushe platform with realistic Nigerian/Hausa names and content

export const mockUser = {
  id: "user_1",
  name: "Aisha Mohammed",
  email: "aisha.m@email.com",
  phone: "+234 801 234 5678",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha",
  dialect: "Kano Hausa",
  region: "Kano",
  level: 12,
  xp: 2450,
  xpToNextLevel: 3000,
  qualityScore: 94,
  streak: 7,
  totalEarnings: 45750,
  availableBalance: 12500,
  pendingBalance: 3200,
  tasksCompleted: 234,
  memberSince: "2024-06-15",
  badges: ["verified", "top-contributor", "quality-master"],
};

export const mockStats = {
  totalContributors: 15420,
  totalDataPoints: 2847593,
  averageQualityScore: 91,
  totalPaidOut: 12500000,
};

export const mockLeaderboard = [
  { id: "1", name: "Ibrahim Yusuf", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ibrahim", points: 8750, rank: 1, region: "Kaduna" },
  { id: "2", name: "Fatima Bello", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima", points: 8234, rank: 2, region: "Kano" },
  { id: "3", name: "Musa Abdullahi", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Musa", points: 7890, rank: 3, region: "Sokoto" },
  { id: "4", name: "Halima Sani", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Halima", points: 7650, rank: 4, region: "Katsina" },
  { id: "5", name: "Umar Garba", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Umar", points: 7420, rank: 5, region: "Bauchi" },
  { id: "6", name: "Zainab Adamu", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zainab", points: 7100, rank: 6, region: "Kano" },
  { id: "7", name: "Ahmad Lawal", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad", points: 6890, rank: 7, region: "Jigawa" },
  { id: "8", name: "Safiya Yusuf", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Safiya", points: 6750, rank: 8, region: "Zamfara" },
  { id: "9", name: "Aisha Mohammed", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Aisha", points: 6500, rank: 9, region: "Kano" },
  { id: "10", name: "Bashir Aliyu", avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bashir", points: 6320, rank: 10, region: "Kaduna" },
];

export type TaskType = "translation" | "audioRecording" | "audioTranscription" | "textClassification" | "ner" | "imageCaptioning" | "sentimentAnalysis";
export type TaskDifficulty = "easy" | "medium" | "hard";

export const mockTasks: Array<{
  id: string;
  type: TaskType;
  title: string;
  titleHa: string;
  description: string;
  descriptionHa: string;
  reward: number;
  estimatedTime: string;
  difficulty: TaskDifficulty;
  category: string;
  available: number;
}> = [
  {
    id: "task_1",
    type: "translation",
    title: "Translate News Article",
    titleHa: "Fassara Labarin Jarida",
    description: "Translate a short news article from English to Hausa",
    descriptionHa: "Fassara labarin jarida gajere daga Turanci zuwa Hausa",
    reward: 150,
    estimatedTime: "5 min",
    difficulty: "easy" as const,
    category: "text",
    available: 45,
  },
  {
    id: "task_2",
    type: "audioRecording",
    title: "Record Hausa Sentences",
    titleHa: "Yi Rikodin Jumlon Hausa",
    description: "Record 10 sentences in clear Hausa pronunciation",
    descriptionHa: "Yi rikodin jumloli 10 a lafazin Hausa mai kyau",
    reward: 200,
    estimatedTime: "8 min",
    difficulty: "easy" as const,
    category: "audio",
    available: 120,
  },
  {
    id: "task_3",
    type: "textClassification",
    title: "Classify Text Topics",
    titleHa: "Rarraba Batutuwan Rubutu",
    description: "Categorize text snippets into topics like news, sports, culture",
    descriptionHa: "Rarraba guntun rubutu zuwa batutuwa kamar labarai, wasanni, al'ada",
    reward: 100,
    estimatedTime: "3 min",
    difficulty: "easy" as const,
    category: "text",
    available: 89,
  },
  {
    id: "task_4",
    type: "audioTranscription",
    title: "Transcribe Audio Clip",
    titleHa: "Rubuta Rikodin Sauti",
    description: "Listen to audio and type what you hear in Hausa",
    descriptionHa: "Saurari sauti kuma rubuta abin da kake ji a Hausa",
    reward: 180,
    estimatedTime: "10 min",
    difficulty: "medium" as const,
    category: "audio",
    available: 34,
  },
  {
    id: "task_5",
    type: "ner",
    title: "Mark Named Entities",
    titleHa: "Alamta Sunayen Wurare",
    description: "Highlight names of people, places, and organizations in text",
    descriptionHa: "Nuna sunayen mutane, wurare, da ƙungiyoyi a cikin rubutu",
    reward: 220,
    estimatedTime: "12 min",
    difficulty: "hard" as const,
    category: "text",
    available: 23,
  },
  {
    id: "task_6",
    type: "imageCaptioning",
    title: "Describe Images",
    titleHa: "Bayyana Hotuna",
    description: "Write descriptive captions for images in Hausa",
    descriptionHa: "Rubuta bayani ga hotuna a Hausa",
    reward: 120,
    estimatedTime: "4 min",
    difficulty: "easy" as const,
    category: "image",
    available: 67,
  },
  {
    id: "task_7",
    type: "sentimentAnalysis",
    title: "Analyze Sentiment",
    titleHa: "Nazarin Ji",
    description: "Determine if text is positive, negative, or neutral",
    descriptionHa: "Tantance ko rubutu yana da kyau, mara kyau, ko tsaka-tsaki",
    reward: 80,
    estimatedTime: "2 min",
    difficulty: "easy" as const,
    category: "text",
    available: 156,
  },
  {
    id: "task_8",
    type: "translation",
    title: "Translate Product Descriptions",
    titleHa: "Fassara Bayanan Kaya",
    description: "Translate e-commerce product descriptions to Hausa",
    descriptionHa: "Fassara bayanan kayayyaki zuwa Hausa",
    reward: 250,
    estimatedTime: "15 min",
    difficulty: "medium" as const,
    category: "text",
    available: 28,
  },
];

export const mockAchievements = [
  {
    id: "ach_1",
    name: "First Steps",
    nameHa: "Matakai na Farko",
    description: "Complete your first task",
    descriptionHa: "Kammala aikinku na farko",
    icon: "🎯",
    rarity: "common" as const,
    unlocked: true,
    unlockedAt: "2024-06-15",
    progress: 1,
    total: 1,
  },
  {
    id: "ach_2",
    name: "Centurion",
    nameHa: "Ɗari",
    description: "Complete 100 tasks",
    descriptionHa: "Kammala ayyuka 100",
    icon: "💯",
    rarity: "rare" as const,
    unlocked: true,
    unlockedAt: "2024-08-20",
    progress: 100,
    total: 100,
  },
  {
    id: "ach_3",
    name: "Quality Champion",
    nameHa: "Zakaran Inganci",
    description: "Maintain 95%+ quality score for 30 days",
    descriptionHa: "Riƙe 95%+ matsayin inganci na kwanaki 30",
    icon: "⭐",
    rarity: "epic" as const,
    unlocked: true,
    unlockedAt: "2024-09-10",
    progress: 30,
    total: 30,
  },
  {
    id: "ach_4",
    name: "Streak Master",
    nameHa: "Jagoran Bi da Bi",
    description: "Maintain a 30-day streak",
    descriptionHa: "Riƙe bi da bi na kwanaki 30",
    icon: "🔥",
    rarity: "epic" as const,
    unlocked: false,
    progress: 7,
    total: 30,
  },
  {
    id: "ach_5",
    name: "Polyglot",
    nameHa: "Mai Harsuna",
    description: "Complete 500 translation tasks",
    descriptionHa: "Kammala ayyukan fassara 500",
    icon: "🌍",
    rarity: "legendary" as const,
    unlocked: false,
    progress: 234,
    total: 500,
  },
  {
    id: "ach_6",
    name: "Voice of Nigeria",
    nameHa: "Muryar Najeriya",
    description: "Record 1000 audio samples",
    descriptionHa: "Yi rikodin samfuran sauti 1000",
    icon: "🎤",
    rarity: "legendary" as const,
    unlocked: false,
    progress: 156,
    total: 1000,
  },
  {
    id: "ach_7",
    name: "Team Player",
    nameHa: "Dan Ƙungiya",
    description: "Join a team and complete 50 tasks together",
    descriptionHa: "Shiga ƙungiya kuma kammala ayyuka 50 tare",
    icon: "🤝",
    rarity: "rare" as const,
    unlocked: false,
    progress: 0,
    total: 50,
  },
  {
    id: "ach_8",
    name: "Early Bird",
    nameHa: "Tsuntsun Safe",
    description: "Complete 10 tasks before 7 AM",
    descriptionHa: "Kammala ayyuka 10 kafin karfe 7 na safe",
    icon: "🌅",
    rarity: "common" as const,
    unlocked: true,
    unlockedAt: "2024-07-01",
    progress: 10,
    total: 10,
  },
];

export const mockDailyChallenges = [
  {
    id: "dc_1",
    title: "Speed Demon",
    titleHa: "Dan Sauri",
    description: "Complete 5 tasks in under 30 minutes",
    descriptionHa: "Kammala ayyuka 5 a cikin mintuna 30",
    reward: 500,
    xpReward: 100,
    progress: 3,
    total: 5,
    expiresAt: "2024-12-15T23:59:59",
  },
  {
    id: "dc_2",
    title: "Perfect Quality",
    titleHa: "Inganci Cikakke",
    description: "Get 100% quality on 3 consecutive tasks",
    descriptionHa: "Samu inganci 100% akan ayyuka 3 a jere",
    reward: 300,
    xpReward: 75,
    progress: 1,
    total: 3,
    expiresAt: "2024-12-15T23:59:59",
  },
  {
    id: "dc_3",
    title: "Audio Master",
    titleHa: "Jagoran Sauti",
    description: "Complete 3 audio recording tasks",
    descriptionHa: "Kammala ayyukan rikodin sauti 3",
    reward: 400,
    xpReward: 80,
    progress: 0,
    total: 3,
    expiresAt: "2024-12-15T23:59:59",
  },
];

export const mockTransactions = [
  { id: "tx_1", type: "earning" as const, amount: 150, description: "Translation Task #1234", date: "2024-12-14T10:30:00", status: "completed" as const },
  { id: "tx_2", type: "earning" as const, amount: 200, description: "Audio Recording Task #1235", date: "2024-12-14T09:15:00", status: "completed" as const },
  { id: "tx_3", type: "withdrawal" as const, amount: 5000, description: "Withdrawal to MTN MoMo", date: "2024-12-13T14:00:00", status: "completed" as const },
  { id: "tx_4", type: "earning" as const, amount: 100, description: "Text Classification #1236", date: "2024-12-13T11:45:00", status: "completed" as const },
  { id: "tx_5", type: "earning" as const, amount: 180, description: "Audio Transcription #1237", date: "2024-12-12T16:20:00", status: "completed" as const },
  { id: "tx_6", type: "bonus" as const, amount: 500, description: "Daily Challenge Reward", date: "2024-12-12T23:59:00", status: "completed" as const },
  { id: "tx_7", type: "earning" as const, amount: 3200, description: "Pending Review Tasks", date: "2024-12-14T12:00:00", status: "pending" as const },
];

export const mockDialects = [
  { id: "kano", name: "Kano Hausa", nameHa: "Hausa Kano" },
  { id: "sokoto", name: "Sokoto Hausa", nameHa: "Hausa Sakkwato" },
  { id: "katsina", name: "Katsina Hausa", nameHa: "Hausa Katsina" },
  { id: "zaria", name: "Zaria Hausa", nameHa: "Hausa Zariya" },
  { id: "bauchi", name: "Bauchi Hausa", nameHa: "Hausa Bauci" },
  { id: "kaduna", name: "Kaduna Hausa", nameHa: "Hausa Kaduna" },
  { id: "niger", name: "Niger Republic Hausa", nameHa: "Hausa Nijar" },
  { id: "ghana", name: "Ghanaian Hausa", nameHa: "Hausa Ghana" },
];

export const mockRecentActivity = [
  { id: "act_1", type: "task_completed", description: "Completed translation task", timestamp: "10 min ago", xp: 25, amount: 150 },
  { id: "act_2", type: "achievement", description: "Unlocked 'Quality Champion' badge", timestamp: "1 hour ago", xp: 100 },
  { id: "act_3", type: "level_up", description: "Reached Level 12!", timestamp: "2 hours ago", xp: 0 },
  { id: "act_4", type: "task_completed", description: "Completed audio recording", timestamp: "3 hours ago", xp: 30, amount: 200 },
  { id: "act_5", type: "streak", description: "7-day streak achieved!", timestamp: "Yesterday", xp: 50 },
];

export const mockTeams = [
  {
    id: "team_1",
    name: "Kano Champions",
    nameHa: "Zakarun Kano",
    description: "Top contributors from Kano State",
    members: 24,
    totalTasks: 4520,
    weeklyRank: 1,
    avatar: "https://api.dicebear.com/7.x/shapes/svg?seed=Kano",
  },
  {
    id: "team_2",
    name: "Northern Stars",
    nameHa: "Tauraruwar Arewa",
    description: "Excellence in data quality",
    members: 18,
    totalTasks: 3890,
    weeklyRank: 2,
    avatar: "https://api.dicebear.com/7.x/shapes/svg?seed=Northern",
  },
  {
    id: "team_3",
    name: "Hausa Legends",
    nameHa: "Jaruman Hausa",
    description: "Masters of translation",
    members: 32,
    totalTasks: 3650,
    weeklyRank: 3,
    avatar: "https://api.dicebear.com/7.x/shapes/svg?seed=Hausa",
  },
];

export const mockProjects = [
  {
    id: "proj_1",
    name: "Hausa News Translation",
    description: "Translating news articles from major Nigerian outlets",
    status: "active" as const,
    progress: 67,
    totalTasks: 5000,
    completedTasks: 3350,
    contributors: 156,
    qualityScore: 92,
    createdAt: "2024-08-01",
  },
  {
    id: "proj_2",
    name: "Voice Recording - Proverbs",
    description: "Recording traditional Hausa proverbs and sayings",
    status: "active" as const,
    progress: 45,
    totalTasks: 2000,
    completedTasks: 900,
    contributors: 89,
    qualityScore: 95,
    createdAt: "2024-09-15",
  },
  {
    id: "proj_3",
    name: "E-commerce Localization",
    description: "Translating product descriptions for Nigerian e-commerce",
    status: "completed" as const,
    progress: 100,
    totalTasks: 1500,
    completedTasks: 1500,
    contributors: 67,
    qualityScore: 89,
    createdAt: "2024-07-10",
  },
  {
    id: "proj_4",
    name: "Hausa Sentiment Analysis Dataset",
    description: "Classifying sentiment in Hausa social media posts and comments",
    status: "completed" as const,
    progress: 100,
    totalTasks: 10000,
    completedTasks: 10000,
    contributors: 234,
    qualityScore: 93,
    createdAt: "2024-05-20",
  },
];

export const mockDatasets = [
  {
    id: "ds_1",
    name: "Hausa-English Parallel Corpus",
    description: "500,000+ sentence pairs for machine translation",
    type: "translation",
    size: "2.3 GB",
    samples: 524000,
    qualityScore: 94,
    downloads: 1250,
    license: "CC BY-SA 4.0",
  },
  {
    id: "ds_2",
    name: "Hausa Speech Dataset",
    description: "200+ hours of labeled Hausa speech",
    type: "audio",
    size: "45 GB",
    samples: 180000,
    qualityScore: 96,
    downloads: 890,
    license: "CC BY 4.0",
  },
  {
    id: "ds_3",
    name: "Hausa Named Entity Dataset",
    description: "Annotated entities in news and social media text",
    type: "ner",
    size: "450 MB",
    samples: 75000,
    qualityScore: 91,
    downloads: 456,
    license: "CC BY-SA 4.0",
  },
];

// Sample task content for task interfaces
export const mockTaskContent = {
  textClassification: {
    text: "Shugaban Najeriya ya ziyarci jihar Kano don bude sabon makarantar kimiya da fasaha.",
    textEn: "The President of Nigeria visited Kano State to open a new science and technology school.",
    labels: [
      { id: "politics", name: "Politics", nameHa: "Siyasa" },
      { id: "education", name: "Education", nameHa: "Ilimi" },
      { id: "technology", name: "Technology", nameHa: "Fasaha" },
      { id: "sports", name: "Sports", nameHa: "Wasanni" },
      { id: "culture", name: "Culture", nameHa: "Al'ada" },
    ],
  },
  translation: {
    source: "The weather in Nigeria is getting hotter due to climate change. Farmers are worried about their crops.",
    targetLanguage: "Hausa",
    glossary: [
      { term: "climate change", translation: "sauyin yanayi" },
      { term: "farmers", translation: "manoma" },
      { term: "crops", translation: "amfanin gona" },
    ],
  },
  audioRecording: {
    prompts: [
      { id: 1, text: "Ina son cin tuwo da miya.", textEn: "I like eating tuwo with soup." },
      { id: 2, text: "Yaya lafiya? Da fatan kowa lafiya.", textEn: "How are you? Hope everyone is well." },
      { id: 3, text: "Makarantar yara tana kusa da kasuwa.", textEn: "The children's school is near the market." },
    ],
  },
  sentimentAnalysis: {
    text: "Wannan abincin yana da daɗi sosai! Zan sake komawa wannan gidan abinci.",
    textEn: "This food is very delicious! I will come back to this restaurant again.",
    options: [
      { id: "positive", name: "Positive", nameHa: "Mai Kyau" },
      { id: "negative", name: "Negative", nameHa: "Maras Kyau" },
      { id: "neutral", name: "Neutral", nameHa: "Tsaka-Tsaki" },
    ],
  },
  ner: {
    text: "Ibrahim Yusuf ya tafi Kano ranar Litinin don ya hadu da Ministan Ilimi a Fadar Gwamnati.",
    textEn: "Ibrahim Yusuf went to Kano on Monday to meet the Minister of Education at the Government House.",
    entityTypes: [
      { id: "person", name: "Person", nameHa: "Mutum", color: "#3B82F6" },
      { id: "location", name: "Location", nameHa: "Wuri", color: "#10B981" },
      { id: "organization", name: "Organization", nameHa: "Kungiya", color: "#F59E0B" },
      { id: "date", name: "Date", nameHa: "Ranar", color: "#8B5CF6" },
    ],
  },
  imageCaptioning: {
    imageUrl: "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800",
    guidelines: "Describe what you see in the image in 1-2 sentences. Include main subjects, actions, and setting.",
    guidelinesHa: "Bayyana abin da kuke gani a hoton a cikin jumloli 1-2. Haɗa da manyan abubuwa, ayyuka, da yanayi.",
  },
};

